using System.IO;
using System.Linq;
using System.Text;
using Essentials.Core.Utility;
using UnityEditor;
using UnityEngine;

namespace Essentials.Internal.GameDirectories
{
    public static class GameDirectoriesSettings
    {
        private static GameDirectoriesSettingsData settingsData;

        /// <summary>
        /// Loads the settings data from the JSON file. If the file doesn't exist, creates new default settings data.
        /// </summary>
        public static void LoadData()
        {
            if (settingsData != null) return;

            settingsData = File.Exists(Path.Combine(Application.dataPath, "EssentialsData", "GameDirectoriesSettingsData.json"))
                ? JsonUtility.FromJson<GameDirectoriesSettingsData>(File.ReadAllText(Path.Combine(Application.dataPath, "EssentialsData", "GameDirectoriesSettingsData.json")))
                : new GameDirectoriesSettingsData();
        }

        /// <summary>
        /// Saves the current settings data to the JSON file. Creates the EssentialsData directory if it doesn't exist.
        /// </summary>
        public static void SaveData()
        {
            string path = Path.Combine(Application.dataPath, "EssentialsData", "GameDirectoriesSettingsData.json");

            if (!Directory.Exists(Path.Combine(Application.dataPath, "EssentialsData"))) Directory.CreateDirectory(Path.Combine(Application.dataPath, "EssentialsData"));
            File.WriteAllText(path, JsonUtility.ToJson(settingsData, true));
            AssetDatabase.Refresh();
        }

        /// <summary>
        /// Gets the configured name for the generated static class.
        /// </summary>
        /// <returns>The class name.</returns>
        public static string GetClassName() => settingsData.className;

        /// <summary>
        /// Gets the configured location (path within Assets) for the generated static class.
        /// </summary>
        /// <returns>The class location path.</returns>
        public static string GetClassLocation() => settingsData.classLocation;

        /// <summary>
        /// Gets the saved game directory data (path and reference pairs).
        /// </summary>
        /// <returns>An array of GameDirectoryData.</returns>
        public static GameDirectoryData[] GetGameDirectoriesData() => JsonUtility.FromJson<Wrapper<GameDirectoryData>>(settingsData.gameDirectoriesData).items;

        /// <summary>
        /// Sets the name for the generated static class.
        /// </summary>
        /// <param name="className">The desired class name.</param>
        public static void SetClassName(string className) => settingsData.className = className;

        /// <summary>
        /// Sets the location (path within Assets) for the generated static class.
        /// </summary>
        /// <param name="classLocation">The desired class location path.</param>
        public static void SetClassLocation(string classLocation) => settingsData.classLocation = classLocation;

        /// <summary>
        /// Sets the game directory data (path and reference pairs) in the settings.
        /// </summary>
        /// <param name="directories">An array of GameDirectoryData to save.</param>
        public static void SetGameDirectoriesData(GameDirectoryData[] directories)
        {
            Wrapper<GameDirectoryData> wrapper = new Wrapper<GameDirectoryData>();
            wrapper.items = directories;
            settingsData.gameDirectoriesData = JsonUtility.ToJson(wrapper);
        }

        /// <summary>
        /// Generates the static C# class file containing properties for accessing game directories.
        /// </summary>
        /// <param name="directories">The array of GameDirectory objects to include in the generated class.</param>
        public static void GenerateClass(GameDirectory[] directories)
        {
            string className = GetClassName();
            string classLocation = GetClassLocation();

            StringBuilder stringBuilder = new StringBuilder();

            stringBuilder.AppendLine("// This file was automatically generated by Essentials Game Directories");
            stringBuilder.AppendLine("// Do not modify this file directly, as changes will be overwritten.");
            stringBuilder.AppendLine("// If you need to change the class name or location, please do so in the Game Directories settings.");
            stringBuilder.AppendLine("using System.IO;");
            stringBuilder.AppendLine("using UnityEngine;");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("namespace Essentials.Core.GameDirectories");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"\tpublic static class {className}");
            stringBuilder.AppendLine("\t{");

            foreach (GameDirectory directory in directories)
            {
                if (string.IsNullOrEmpty(directory.reference)) continue;

                stringBuilder.AppendLine($"\t\tpublic static string {directory.reference}");
                stringBuilder.AppendLine("\t\t{");
                stringBuilder.AppendLine("\t\t\tget");
                stringBuilder.AppendLine("\t\t\t{");
                stringBuilder.AppendLine($"\t\t\t\tstring path = Path.Combine(Application.persistentDataPath, {string.Join(", ", directory.path.Split("/").Select(x => $"\"{x}\""))});");
                stringBuilder.AppendLine("\t\t\t\tif (!Directory.Exists(path)) Directory.CreateDirectory(path);");
                stringBuilder.AppendLine("\t\t\t\treturn path;");
                stringBuilder.AppendLine("\t\t\t}");
                stringBuilder.AppendLine("\t\t}");
            }

            stringBuilder.AppendLine("\t}");
            stringBuilder.AppendLine("}");

            string classPath = $"{Path.Combine(classLocation, className)}.cs";

            if (AssetDatabase.LoadAssetAtPath<MonoScript>(classPath) != null) AssetDatabase.DeleteAsset(classPath);

            StreamWriter streamWriter = new StreamWriter(Application.dataPath + classPath[6..]);
            streamWriter.Write(stringBuilder.ToString());
            streamWriter.Close();

            AssetDatabase.Refresh();
        }
    }
}